Add Table of Content Support
ttu-ttu/ebook-reader pull request #156
Opened 2022-05-16 20:52 UTC by Renji-XD

cloeses #26 

- adds support for book internal toc in pagination mode and fix an ux issue for continuation mode in regards with configured margins
- adds keybinds for next/previous chapter on desktop
- as discussed before no fallback / retrospective build, only new imported books will build the required data
- as discussed before progression is based on element position and not on current explored characters
- similar to explored character count the progress is based on the right/top area of the element and will therefore typically not reach 100% of a book etc.

2022-05-19 12:43 UTC, ChaseOxide commented on apps/web/src/lib/components/book-reader/book-reader-continuous/book-reader-continuous.svelte
> +  const sectionData: Map<string, SectionWithProgress> = new Map();
For future reference you can actually do `const sectionData = new Map<string, SectionWithProgress>();`

2022-05-19 12:47 UTC, ChaseOxide commented on apps/web/src/lib/components/book-reader/book-reader-paginated/page-manager-paginated.ts
> +    if (ref && this.sectionData.has(ref)) {
For such code I usually prefer early return, like
`if (!ref || !this.sectionData.has(ref)) return`

2022-05-19 13:04 UTC, ChaseOxide requested changes
- ToC button should be in the top header's most left item
- I think the ToC popup's background colors are reversed (expect darker background on the book content, popup itself remain "natural")

What I've found so far

2022-05-19 14:20 UTC, Renji-XD commented
> * ToC button should be in the top header's most left item
> * I think the ToC popup's background colors are reversed (expect darker background on the book content, popup itself remain "natural")

 - Not sure how much it is used, but i thought one click less is more convenient for a on page feature (therefore also no keybind) and it may also looks better than having an overlapping animation from the header. up to you
 - I am not sure what you mean with "natural" - i though it make sense to have a more darker background for a darker theme and vice versa. maybe just drop me the colors you prefer for dark / light mode and i can replace them

2022-05-25 13:48 UTC, ChaseOxide commented
> Not sure how much it is used, but i thought one click less is more convenient for a on page feature (therefore also no keybind) and it may also looks better than having an overlapping animation from the header.
It took me few minutes to find the icon, just think the button is in an unnatural position, since from my experience these buttons are usually placed at the top.

> Also the header is kind of relatively full on mobile already - moving the icon there will not leave much place for much more in the future
If space is needed we'll have to make a dropdown, I still prefer more clicks over putting it at the bottom

For the pop out background, the sidebar background should be the same as the book's background color (if you're trying to stick with the reader's theme). Backdrop background should be the same as the dialog's (bg-black/[.32]), with the elevation of 16 (mdc-elevation--z16).
(Kind of hinting it should use dialogManager, but I think it's fine if it's separate)

2022-05-28 01:29 UTC, merged